import "./basic/hello/basic-hello.ts";
import "./basic/button/basic-button.ts";
import "./basic/counter/basic-counter.ts";
import "./basic/number/basic-number.ts";
import "./basic/pluralize/basic-pluralize.ts";
import "./card/mediaqueries/card-mediaqueries.ts";
import "./context/media/context-media.ts";
import "./form/checkbox/form-checkbox.ts";
import "./form/combobox/form-combobox.ts";
import "./form/inplace-edit/form-inplace-edit.ts";
import "./form/listbox/form-listbox.ts";
import "./form/radiogroup/form-radiogroup.ts";
import "./form/spinbutton/form-spinbutton.ts";
import "./form/textbox/form-textbox.ts";
import "./module/carousel/module-carousel.ts";
import "./module/catalog/module-catalog.ts";
import "./module/codeblock/module-codeblock.ts";
import "./module/dialog/module-dialog.ts";
import "./module/lazyload/module-lazyload.ts";
import "./module/listnav/module-listnav.ts";
import "./module/pagination/module-pagination.ts";
import "./module/scrollarea/module-scrollarea.ts";
import "./module/tabgroup/module-tabgroup.ts";
import "./module/todo/module-todo.ts";

// Structural-only custom elements
customElements.define("card-callout", class extends HTMLElement {});
customElements.define("module-demo", class extends HTMLElement {});
customElements.define("module-toc", class extends HTMLElement {});
customElements.define("section-hero", class extends HTMLElement {});
customElements.define("section-menu", class extends HTMLElement {});
